package com.example.notificationreader.decision

enum class DecisionRuleId {
    RAW_EVENT_RECEIVED,
    EVENT_EXTRACTED,
    IGNORE_SYSTEM,
    IGNORE_SERVICE,
    IGNORE_EMPTY,
    MEANINGFUL_NOTIFICATION,
    DUPLICATE_CONTENT_WITHIN_WINDOW,
    HISTORY_ALLOWED,
    HISTORY_SKIPPED,
    SPEECH_ALLOWED,
    SPEECH_PREFS_DISABLED,
    SPEECH_DUPLICATE_KEY,
    SPEECH_DUPLICATE_FINGERPRINT,
    SPEECH_TEMPLATE_SELECTED,
    SPEECH_EXECUTED
}
